[package]
name = "maze-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", default-features = false, features = ["png"] }
irrgarten = "0.1.1"
rand = "0.8.5"
thiserror = "2.0.4"
